// Service category color variants based on Tailwind color palette
export type ServiceCategoryVariant =
  | "blue"
  | "indigo"
  | "purple"
  | "pink"
  | "rose"
  | "red"
  | "orange"
  | "amber"
  | "emerald"
  | "teal"
  | "cyan"
  | "sky"
  | "green"
  | "lime"
  | "yellow"
  | "violet"
  | "fuchsia"
  | "slate"
  | "gray"
  | "zinc"
  | "stone"
  | "neutral"
  | "blue-gray"
  | "warm-gray"
  | "cool-gray"
  | "true-gray"
  | "red-orange"
  | "yellow-green"
  | "blue-green"
  | "purple-blue"
  | "blue-dark"
  | "indigo-dark"
  | "purple-dark"
  | "pink-dark"
  | "rose-dark"
  | "red-dark"
  | "orange-dark"
  | "amber-dark"
  | "emerald-dark"
  | "teal-dark"
  | "cyan-dark"
  | "sky-dark"
  | "green-dark"
  | "lime-dark"
  | "yellow-dark"
  | "violet-dark"
  | "fuchsia-dark"
  | "blue-400"
  | "indigo-400"
  | "purple-400"
  | "pink-400"
  | "rose-400"
  | "red-400"
  | "orange-400"
  | "amber-400"
  | "emerald-400"
  | "teal-400"
  | "cyan-400"
  | "sky-400"
  | "green-400"
  | "lime-400"
  | "yellow-400"
  | "violet-400"
  | "fuchsia-400"
  | "blue-700"
  | "indigo-700"
  | "purple-700"
  | "pink-700"
  | "rose-700"
  | "red-700"
  | "orange-700"
  | "amber-700"
  | "emerald-700"
  | "teal-700"
  | "cyan-700"
  | "sky-700"
  | "green-700"
  | "lime-700"
  | "yellow-700"
  | "violet-700"
  | "fuchsia-700"

export interface ServiceCategoryVariantConfig {
  id: ServiceCategoryVariant
  name: string
  bg: string
  bgLight: string
  bgHover: string
  text: string
  textLight: string
  border: string
  ring: string
}

export const SERVICE_CATEGORY_VARIANTS: Record<ServiceCategoryVariant, ServiceCategoryVariantConfig> = {
  blue: {
    id: "blue",
    name: "כחול",
    bg: "bg-primary",
    bgLight: "bg-primary/10",
    bgHover: "hover:bg-primary/90",
    text: "text-primary",
    textLight: "text-primary-foreground",
    border: "border-primary/20",
    ring: "ring-primary",
  },
  indigo: {
    id: "indigo",
    name: "אינדיגו",
    bg: "bg-indigo-600",
    bgLight: "bg-indigo-50",
    bgHover: "hover:bg-indigo-700",
    text: "text-indigo-600",
    textLight: "text-indigo-50",
    border: "border-indigo-200",
    ring: "ring-indigo-500",
  },
  purple: {
    id: "purple",
    name: "סגול",
    bg: "bg-purple-600",
    bgLight: "bg-purple-50",
    bgHover: "hover:bg-purple-700",
    text: "text-purple-600",
    textLight: "text-purple-50",
    border: "border-purple-200",
    ring: "ring-purple-500",
  },
  pink: {
    id: "pink",
    name: "ורוד",
    bg: "bg-pink-600",
    bgLight: "bg-pink-50",
    bgHover: "hover:bg-pink-700",
    text: "text-pink-600",
    textLight: "text-pink-50",
    border: "border-pink-200",
    ring: "ring-pink-500",
  },
  rose: {
    id: "rose",
    name: "ורוד כהה",
    bg: "bg-rose-600",
    bgLight: "bg-rose-50",
    bgHover: "hover:bg-rose-700",
    text: "text-rose-600",
    textLight: "text-rose-50",
    border: "border-rose-200",
    ring: "ring-rose-500",
  },
  red: {
    id: "red",
    name: "אדום",
    bg: "bg-red-600",
    bgLight: "bg-red-50",
    bgHover: "hover:bg-red-700",
    text: "text-red-600",
    textLight: "text-red-50",
    border: "border-red-200",
    ring: "ring-red-500",
  },
  orange: {
    id: "orange",
    name: "כתום",
    bg: "bg-orange-600",
    bgLight: "bg-orange-50",
    bgHover: "hover:bg-orange-700",
    text: "text-orange-600",
    textLight: "text-orange-50",
    border: "border-orange-200",
    ring: "ring-orange-500",
  },
  amber: {
    id: "amber",
    name: "ענבר",
    bg: "bg-amber-600",
    bgLight: "bg-amber-50",
    bgHover: "hover:bg-amber-700",
    text: "text-amber-600",
    textLight: "text-amber-50",
    border: "border-amber-200",
    ring: "ring-amber-500",
  },
  emerald: {
    id: "emerald",
    name: "אזמרגד",
    bg: "bg-emerald-600",
    bgLight: "bg-emerald-50",
    bgHover: "hover:bg-emerald-700",
    text: "text-emerald-600",
    textLight: "text-emerald-50",
    border: "border-emerald-200",
    ring: "ring-emerald-500",
  },
  teal: {
    id: "teal",
    name: "טורקיז",
    bg: "bg-teal-600",
    bgLight: "bg-teal-50",
    bgHover: "hover:bg-teal-700",
    text: "text-teal-600",
    textLight: "text-teal-50",
    border: "border-teal-200",
    ring: "ring-teal-500",
  },
  cyan: {
    id: "cyan",
    name: "ציאן",
    bg: "bg-cyan-600",
    bgLight: "bg-cyan-50",
    bgHover: "hover:bg-cyan-700",
    text: "text-cyan-600",
    textLight: "text-cyan-50",
    border: "border-cyan-200",
    ring: "ring-cyan-500",
  },
  sky: {
    id: "sky",
    name: "שמיים",
    bg: "bg-sky-600",
    bgLight: "bg-sky-50",
    bgHover: "hover:bg-sky-700",
    text: "text-sky-600",
    textLight: "text-sky-50",
    border: "border-sky-200",
    ring: "ring-sky-500",
  },
  green: {
    id: "green",
    name: "ירוק",
    bg: "bg-green-600",
    bgLight: "bg-green-50",
    bgHover: "hover:bg-green-700",
    text: "text-green-600",
    textLight: "text-green-50",
    border: "border-green-200",
    ring: "ring-green-500",
  },
  lime: {
    id: "lime",
    name: "ליים",
    bg: "bg-lime-600",
    bgLight: "bg-lime-50",
    bgHover: "hover:bg-lime-700",
    text: "text-lime-600",
    textLight: "text-lime-50",
    border: "border-lime-200",
    ring: "ring-lime-500",
  },
  yellow: {
    id: "yellow",
    name: "צהוב",
    bg: "bg-yellow-600",
    bgLight: "bg-yellow-50",
    bgHover: "hover:bg-yellow-700",
    text: "text-yellow-600",
    textLight: "text-yellow-50",
    border: "border-yellow-200",
    ring: "ring-yellow-500",
  },
  violet: {
    id: "violet",
    name: "סגול כהה",
    bg: "bg-violet-600",
    bgLight: "bg-violet-50",
    bgHover: "hover:bg-violet-700",
    text: "text-violet-600",
    textLight: "text-violet-50",
    border: "border-violet-200",
    ring: "ring-violet-500",
  },
  fuchsia: {
    id: "fuchsia",
    name: "פוקסיה",
    bg: "bg-fuchsia-600",
    bgLight: "bg-fuchsia-50",
    bgHover: "hover:bg-fuchsia-700",
    text: "text-fuchsia-600",
    textLight: "text-fuchsia-50",
    border: "border-fuchsia-200",
    ring: "ring-fuchsia-500",
  },
  slate: {
    id: "slate",
    name: "צפחה",
    bg: "bg-slate-600",
    bgLight: "bg-slate-50",
    bgHover: "hover:bg-slate-700",
    text: "text-slate-600",
    textLight: "text-slate-50",
    border: "border-slate-200",
    ring: "ring-slate-500",
  },
  gray: {
    id: "gray",
    name: "אפור",
    bg: "bg-gray-600",
    bgLight: "bg-gray-50",
    bgHover: "hover:bg-gray-700",
    text: "text-gray-600",
    textLight: "text-gray-50",
    border: "border-gray-200",
    ring: "ring-gray-500",
  },
  zinc: {
    id: "zinc",
    name: "אבץ",
    bg: "bg-zinc-600",
    bgLight: "bg-zinc-50",
    bgHover: "hover:bg-zinc-700",
    text: "text-zinc-600",
    textLight: "text-zinc-50",
    border: "border-zinc-200",
    ring: "ring-zinc-500",
  },
  stone: {
    id: "stone",
    name: "אבן",
    bg: "bg-stone-600",
    bgLight: "bg-stone-50",
    bgHover: "hover:bg-stone-700",
    text: "text-stone-600",
    textLight: "text-stone-50",
    border: "border-stone-200",
    ring: "ring-stone-500",
  },
  neutral: {
    id: "neutral",
    name: "ניטרלי",
    bg: "bg-neutral-600",
    bgLight: "bg-neutral-50",
    bgHover: "hover:bg-neutral-700",
    text: "text-neutral-600",
    textLight: "text-neutral-50",
    border: "border-neutral-200",
    ring: "ring-neutral-500",
  },
  "blue-gray": {
    id: "blue-gray",
    name: "כחול-אפור",
    bg: "bg-slate-500",
    bgLight: "bg-slate-50",
    bgHover: "hover:bg-slate-600",
    text: "text-slate-600",
    textLight: "text-slate-50",
    border: "border-slate-200",
    ring: "ring-slate-400",
  },
  "warm-gray": {
    id: "warm-gray",
    name: "אפור חם",
    bg: "bg-stone-500",
    bgLight: "bg-stone-50",
    bgHover: "hover:bg-stone-600",
    text: "text-stone-600",
    textLight: "text-stone-50",
    border: "border-stone-200",
    ring: "ring-stone-400",
  },
  "cool-gray": {
    id: "cool-gray",
    name: "אפור קר",
    bg: "bg-gray-500",
    bgLight: "bg-gray-50",
    bgHover: "hover:bg-gray-600",
    text: "text-gray-600",
    textLight: "text-gray-50",
    border: "border-gray-200",
    ring: "ring-gray-400",
  },
  "true-gray": {
    id: "true-gray",
    name: "אפור אמיתי",
    bg: "bg-neutral-500",
    bgLight: "bg-neutral-50",
    bgHover: "hover:bg-neutral-600",
    text: "text-neutral-600",
    textLight: "text-neutral-50",
    border: "border-neutral-200",
    ring: "ring-neutral-400",
  },
  "red-orange": {
    id: "red-orange",
    name: "אדום-כתום",
    bg: "bg-orange-500",
    bgLight: "bg-orange-50",
    bgHover: "hover:bg-orange-600",
    text: "text-orange-600",
    textLight: "text-orange-50",
    border: "border-orange-200",
    ring: "ring-orange-400",
  },
  "yellow-green": {
    id: "yellow-green",
    name: "צהוב-ירוק",
    bg: "bg-lime-500",
    bgLight: "bg-lime-50",
    bgHover: "hover:bg-lime-600",
    text: "text-lime-600",
    textLight: "text-lime-50",
    border: "border-lime-200",
    ring: "ring-lime-400",
  },
  "blue-green": {
    id: "blue-green",
    name: "כחול-ירוק",
    bg: "bg-teal-500",
    bgLight: "bg-teal-50",
    bgHover: "hover:bg-teal-600",
    text: "text-teal-600",
    textLight: "text-teal-50",
    border: "border-teal-200",
    ring: "ring-teal-400",
  },
  "purple-blue": {
    id: "purple-blue",
    name: "סגול-כחול",
    bg: "bg-indigo-500",
    bgLight: "bg-indigo-50",
    bgHover: "hover:bg-indigo-600",
    text: "text-indigo-600",
    textLight: "text-indigo-50",
    border: "border-indigo-200",
    ring: "ring-indigo-400",
  },
  "blue-dark": {
    id: "blue-dark",
    name: "כחול כהה",
    bg: "bg-primary",
    bgLight: "bg-primary/20",
    bgHover: "hover:bg-primary/90",
    text: "text-primary",
    textLight: "text-primary-foreground",
    border: "border-primary/30",
    ring: "ring-primary",
  },
  "indigo-dark": {
    id: "indigo-dark",
    name: "אינדיגו כהה",
    bg: "bg-indigo-800",
    bgLight: "bg-indigo-100",
    bgHover: "hover:bg-indigo-900",
    text: "text-indigo-800",
    textLight: "text-indigo-50",
    border: "border-indigo-300",
    ring: "ring-indigo-600",
  },
  "purple-dark": {
    id: "purple-dark",
    name: "סגול כהה",
    bg: "bg-purple-800",
    bgLight: "bg-purple-100",
    bgHover: "hover:bg-purple-900",
    text: "text-purple-800",
    textLight: "text-purple-50",
    border: "border-purple-300",
    ring: "ring-purple-600",
  },
  "pink-dark": {
    id: "pink-dark",
    name: "ורוד כהה",
    bg: "bg-pink-800",
    bgLight: "bg-pink-100",
    bgHover: "hover:bg-pink-900",
    text: "text-pink-800",
    textLight: "text-pink-50",
    border: "border-pink-300",
    ring: "ring-pink-600",
  },
  "rose-dark": {
    id: "rose-dark",
    name: "ורוד כהה מאוד",
    bg: "bg-rose-800",
    bgLight: "bg-rose-100",
    bgHover: "hover:bg-rose-900",
    text: "text-rose-800",
    textLight: "text-rose-50",
    border: "border-rose-300",
    ring: "ring-rose-600",
  },
  "red-dark": {
    id: "red-dark",
    name: "אדום כהה",
    bg: "bg-red-800",
    bgLight: "bg-red-100",
    bgHover: "hover:bg-red-900",
    text: "text-red-800",
    textLight: "text-red-50",
    border: "border-red-300",
    ring: "ring-red-600",
  },
  "orange-dark": {
    id: "orange-dark",
    name: "כתום כהה",
    bg: "bg-orange-800",
    bgLight: "bg-orange-100",
    bgHover: "hover:bg-orange-900",
    text: "text-orange-800",
    textLight: "text-orange-50",
    border: "border-orange-300",
    ring: "ring-orange-600",
  },
  "amber-dark": {
    id: "amber-dark",
    name: "ענבר כהה",
    bg: "bg-amber-800",
    bgLight: "bg-amber-100",
    bgHover: "hover:bg-amber-900",
    text: "text-amber-800",
    textLight: "text-amber-50",
    border: "border-amber-300",
    ring: "ring-amber-600",
  },
  "emerald-dark": {
    id: "emerald-dark",
    name: "אזמרגד כהה",
    bg: "bg-emerald-800",
    bgLight: "bg-emerald-100",
    bgHover: "hover:bg-emerald-900",
    text: "text-emerald-800",
    textLight: "text-emerald-50",
    border: "border-emerald-300",
    ring: "ring-emerald-600",
  },
  "teal-dark": {
    id: "teal-dark",
    name: "טורקיז כהה",
    bg: "bg-teal-800",
    bgLight: "bg-teal-100",
    bgHover: "hover:bg-teal-900",
    text: "text-teal-800",
    textLight: "text-teal-50",
    border: "border-teal-300",
    ring: "ring-teal-600",
  },
  "cyan-dark": {
    id: "cyan-dark",
    name: "ציאן כהה",
    bg: "bg-cyan-800",
    bgLight: "bg-cyan-100",
    bgHover: "hover:bg-cyan-900",
    text: "text-cyan-800",
    textLight: "text-cyan-50",
    border: "border-cyan-300",
    ring: "ring-cyan-600",
  },
  "sky-dark": {
    id: "sky-dark",
    name: "שמיים כהה",
    bg: "bg-sky-800",
    bgLight: "bg-sky-100",
    bgHover: "hover:bg-sky-900",
    text: "text-sky-800",
    textLight: "text-sky-50",
    border: "border-sky-300",
    ring: "ring-sky-600",
  },
  "green-dark": {
    id: "green-dark",
    name: "ירוק כהה",
    bg: "bg-green-800",
    bgLight: "bg-green-100",
    bgHover: "hover:bg-green-900",
    text: "text-green-800",
    textLight: "text-green-50",
    border: "border-green-300",
    ring: "ring-green-600",
  },
  "lime-dark": {
    id: "lime-dark",
    name: "ליים כהה",
    bg: "bg-lime-800",
    bgLight: "bg-lime-100",
    bgHover: "hover:bg-lime-900",
    text: "text-lime-800",
    textLight: "text-lime-50",
    border: "border-lime-300",
    ring: "ring-lime-600",
  },
  "yellow-dark": {
    id: "yellow-dark",
    name: "צהוב כהה",
    bg: "bg-yellow-800",
    bgLight: "bg-yellow-100",
    bgHover: "hover:bg-yellow-900",
    text: "text-yellow-800",
    textLight: "text-yellow-50",
    border: "border-yellow-300",
    ring: "ring-yellow-600",
  },
  "violet-dark": {
    id: "violet-dark",
    name: "סגול כהה מאוד",
    bg: "bg-violet-800",
    bgLight: "bg-violet-100",
    bgHover: "hover:bg-violet-900",
    text: "text-violet-800",
    textLight: "text-violet-50",
    border: "border-violet-300",
    ring: "ring-violet-600",
  },
  "fuchsia-dark": {
    id: "fuchsia-dark",
    name: "פוקסיה כהה",
    bg: "bg-fuchsia-800",
    bgLight: "bg-fuchsia-100",
    bgHover: "hover:bg-fuchsia-900",
    text: "text-fuchsia-800",
    textLight: "text-fuchsia-50",
    border: "border-fuchsia-300",
    ring: "ring-fuchsia-600",
  },
  "blue-400": {
    id: "blue-400",
    name: "כחול בהיר",
    bg: "bg-primary/40",
    bgLight: "bg-primary/10",
    bgHover: "hover:bg-primary/50",
    text: "text-primary",
    textLight: "text-primary-foreground",
    border: "border-primary/20",
    ring: "ring-primary/40",
  },
  "indigo-400": {
    id: "indigo-400",
    name: "אינדיגו בהיר",
    bg: "bg-indigo-400",
    bgLight: "bg-indigo-50",
    bgHover: "hover:bg-indigo-500",
    text: "text-indigo-700",
    textLight: "text-indigo-50",
    border: "border-indigo-200",
    ring: "ring-indigo-400",
  },
  "purple-400": {
    id: "purple-400",
    name: "סגול בהיר",
    bg: "bg-purple-400",
    bgLight: "bg-purple-50",
    bgHover: "hover:bg-purple-500",
    text: "text-purple-700",
    textLight: "text-purple-50",
    border: "border-purple-200",
    ring: "ring-purple-400",
  },
  "pink-400": {
    id: "pink-400",
    name: "ורוד בהיר",
    bg: "bg-pink-400",
    bgLight: "bg-pink-50",
    bgHover: "hover:bg-pink-500",
    text: "text-pink-700",
    textLight: "text-pink-50",
    border: "border-pink-200",
    ring: "ring-pink-400",
  },
  "rose-400": {
    id: "rose-400",
    name: "ורוד בהיר כהה",
    bg: "bg-rose-400",
    bgLight: "bg-rose-50",
    bgHover: "hover:bg-rose-500",
    text: "text-rose-700",
    textLight: "text-rose-50",
    border: "border-rose-200",
    ring: "ring-rose-400",
  },
  "red-400": {
    id: "red-400",
    name: "אדום בהיר",
    bg: "bg-red-400",
    bgLight: "bg-red-50",
    bgHover: "hover:bg-red-500",
    text: "text-red-700",
    textLight: "text-red-50",
    border: "border-red-200",
    ring: "ring-red-400",
  },
  "orange-400": {
    id: "orange-400",
    name: "כתום בהיר",
    bg: "bg-orange-400",
    bgLight: "bg-orange-50",
    bgHover: "hover:bg-orange-500",
    text: "text-orange-700",
    textLight: "text-orange-50",
    border: "border-orange-200",
    ring: "ring-orange-400",
  },
  "amber-400": {
    id: "amber-400",
    name: "ענבר בהיר",
    bg: "bg-amber-400",
    bgLight: "bg-amber-50",
    bgHover: "hover:bg-amber-500",
    text: "text-amber-700",
    textLight: "text-amber-50",
    border: "border-amber-200",
    ring: "ring-amber-400",
  },
  "emerald-400": {
    id: "emerald-400",
    name: "אזמרגד בהיר",
    bg: "bg-emerald-400",
    bgLight: "bg-emerald-50",
    bgHover: "hover:bg-emerald-500",
    text: "text-emerald-700",
    textLight: "text-emerald-50",
    border: "border-emerald-200",
    ring: "ring-emerald-400",
  },
  "teal-400": {
    id: "teal-400",
    name: "טורקיז בהיר",
    bg: "bg-teal-400",
    bgLight: "bg-teal-50",
    bgHover: "hover:bg-teal-500",
    text: "text-teal-700",
    textLight: "text-teal-50",
    border: "border-teal-200",
    ring: "ring-teal-400",
  },
  "cyan-400": {
    id: "cyan-400",
    name: "ציאן בהיר",
    bg: "bg-cyan-400",
    bgLight: "bg-cyan-50",
    bgHover: "hover:bg-cyan-500",
    text: "text-cyan-700",
    textLight: "text-cyan-50",
    border: "border-cyan-200",
    ring: "ring-cyan-400",
  },
  "sky-400": {
    id: "sky-400",
    name: "שמיים בהיר",
    bg: "bg-sky-400",
    bgLight: "bg-sky-50",
    bgHover: "hover:bg-sky-500",
    text: "text-sky-700",
    textLight: "text-sky-50",
    border: "border-sky-200",
    ring: "ring-sky-400",
  },
  "green-400": {
    id: "green-400",
    name: "ירוק בהיר",
    bg: "bg-green-400",
    bgLight: "bg-green-50",
    bgHover: "hover:bg-green-500",
    text: "text-green-700",
    textLight: "text-green-50",
    border: "border-green-200",
    ring: "ring-green-400",
  },
  "lime-400": {
    id: "lime-400",
    name: "ליים בהיר",
    bg: "bg-lime-400",
    bgLight: "bg-lime-50",
    bgHover: "hover:bg-lime-500",
    text: "text-lime-700",
    textLight: "text-lime-50",
    border: "border-lime-200",
    ring: "ring-lime-400",
  },
  "yellow-400": {
    id: "yellow-400",
    name: "צהוב בהיר",
    bg: "bg-yellow-400",
    bgLight: "bg-yellow-50",
    bgHover: "hover:bg-yellow-500",
    text: "text-yellow-700",
    textLight: "text-yellow-50",
    border: "border-yellow-200",
    ring: "ring-yellow-400",
  },
  "violet-400": {
    id: "violet-400",
    name: "סגול בהיר כהה",
    bg: "bg-violet-400",
    bgLight: "bg-violet-50",
    bgHover: "hover:bg-violet-500",
    text: "text-violet-700",
    textLight: "text-violet-50",
    border: "border-violet-200",
    ring: "ring-violet-400",
  },
  "fuchsia-400": {
    id: "fuchsia-400",
    name: "פוקסיה בהיר",
    bg: "bg-fuchsia-400",
    bgLight: "bg-fuchsia-50",
    bgHover: "hover:bg-fuchsia-500",
    text: "text-fuchsia-700",
    textLight: "text-fuchsia-50",
    border: "border-fuchsia-200",
    ring: "ring-fuchsia-400",
  },
  "blue-700": {
    id: "blue-700",
    name: "כחול בינוני",
    bg: "bg-primary/90",
    bgLight: "bg-primary/20",
    bgHover: "hover:bg-primary",
    text: "text-primary",
    textLight: "text-primary-foreground",
    border: "border-primary/30",
    ring: "ring-primary",
  },
  "indigo-700": {
    id: "indigo-700",
    name: "אינדיגו בינוני",
    bg: "bg-indigo-700",
    bgLight: "bg-indigo-100",
    bgHover: "hover:bg-indigo-800",
    text: "text-indigo-700",
    textLight: "text-indigo-50",
    border: "border-indigo-300",
    ring: "ring-indigo-500",
  },
  "purple-700": {
    id: "purple-700",
    name: "סגול בינוני",
    bg: "bg-purple-700",
    bgLight: "bg-purple-100",
    bgHover: "hover:bg-purple-800",
    text: "text-purple-700",
    textLight: "text-purple-50",
    border: "border-purple-300",
    ring: "ring-purple-500",
  },
  "pink-700": {
    id: "pink-700",
    name: "ורוד בינוני",
    bg: "bg-pink-700",
    bgLight: "bg-pink-100",
    bgHover: "hover:bg-pink-800",
    text: "text-pink-700",
    textLight: "text-pink-50",
    border: "border-pink-300",
    ring: "ring-pink-500",
  },
  "rose-700": {
    id: "rose-700",
    name: "ורוד בינוני כהה",
    bg: "bg-rose-700",
    bgLight: "bg-rose-100",
    bgHover: "hover:bg-rose-800",
    text: "text-rose-700",
    textLight: "text-rose-50",
    border: "border-rose-300",
    ring: "ring-rose-500",
  },
  "red-700": {
    id: "red-700",
    name: "אדום בינוני",
    bg: "bg-red-700",
    bgLight: "bg-red-100",
    bgHover: "hover:bg-red-800",
    text: "text-red-700",
    textLight: "text-red-50",
    border: "border-red-300",
    ring: "ring-red-500",
  },
  "orange-700": {
    id: "orange-700",
    name: "כתום בינוני",
    bg: "bg-orange-700",
    bgLight: "bg-orange-100",
    bgHover: "hover:bg-orange-800",
    text: "text-orange-700",
    textLight: "text-orange-50",
    border: "border-orange-300",
    ring: "ring-orange-500",
  },
  "amber-700": {
    id: "amber-700",
    name: "ענבר בינוני",
    bg: "bg-amber-700",
    bgLight: "bg-amber-100",
    bgHover: "hover:bg-amber-800",
    text: "text-amber-700",
    textLight: "text-amber-50",
    border: "border-amber-300",
    ring: "ring-amber-500",
  },
  "emerald-700": {
    id: "emerald-700",
    name: "אזמרגד בינוני",
    bg: "bg-emerald-700",
    bgLight: "bg-emerald-100",
    bgHover: "hover:bg-emerald-800",
    text: "text-emerald-700",
    textLight: "text-emerald-50",
    border: "border-emerald-300",
    ring: "ring-emerald-500",
  },
  "teal-700": {
    id: "teal-700",
    name: "טורקיז בינוני",
    bg: "bg-teal-700",
    bgLight: "bg-teal-100",
    bgHover: "hover:bg-teal-800",
    text: "text-teal-700",
    textLight: "text-teal-50",
    border: "border-teal-300",
    ring: "ring-teal-500",
  },
  "cyan-700": {
    id: "cyan-700",
    name: "ציאן בינוני",
    bg: "bg-cyan-700",
    bgLight: "bg-cyan-100",
    bgHover: "hover:bg-cyan-800",
    text: "text-cyan-700",
    textLight: "text-cyan-50",
    border: "border-cyan-300",
    ring: "ring-cyan-500",
  },
  "sky-700": {
    id: "sky-700",
    name: "שמיים בינוני",
    bg: "bg-sky-700",
    bgLight: "bg-sky-100",
    bgHover: "hover:bg-sky-800",
    text: "text-sky-700",
    textLight: "text-sky-50",
    border: "border-sky-300",
    ring: "ring-sky-500",
  },
  "green-700": {
    id: "green-700",
    name: "ירוק בינוני",
    bg: "bg-green-700",
    bgLight: "bg-green-100",
    bgHover: "hover:bg-green-800",
    text: "text-green-700",
    textLight: "text-green-50",
    border: "border-green-300",
    ring: "ring-green-500",
  },
  "lime-700": {
    id: "lime-700",
    name: "ליים בינוני",
    bg: "bg-lime-700",
    bgLight: "bg-lime-100",
    bgHover: "hover:bg-lime-800",
    text: "text-lime-700",
    textLight: "text-lime-50",
    border: "border-lime-300",
    ring: "ring-lime-500",
  },
  "yellow-700": {
    id: "yellow-700",
    name: "צהוב בינוני",
    bg: "bg-yellow-700",
    bgLight: "bg-yellow-100",
    bgHover: "hover:bg-yellow-800",
    text: "text-yellow-700",
    textLight: "text-yellow-50",
    border: "border-yellow-300",
    ring: "ring-yellow-500",
  },
  "violet-700": {
    id: "violet-700",
    name: "סגול בינוני כהה",
    bg: "bg-violet-700",
    bgLight: "bg-violet-100",
    bgHover: "hover:bg-violet-800",
    text: "text-violet-700",
    textLight: "text-violet-50",
    border: "border-violet-300",
    ring: "ring-violet-500",
  },
  "fuchsia-700": {
    id: "fuchsia-700",
    name: "פוקסיה בינוני",
    bg: "bg-fuchsia-700",
    bgLight: "bg-fuchsia-100",
    bgHover: "hover:bg-fuchsia-800",
    text: "text-fuchsia-700",
    textLight: "text-fuchsia-50",
    border: "border-fuchsia-300",
    ring: "ring-fuchsia-500",
  },
}

export const SERVICE_CATEGORY_VARIANTS_ARRAY = Object.values(SERVICE_CATEGORY_VARIANTS)
